### ISSUE TITLE
Why two interfaces for generator and receiver?

### ISSUE THREAD

**Issue by chengyu** [P4-vSwitch/vagrant#2]
Hi,

Sorry, I'm new to the DPDK and PISCES. Please forgive me if I asked some questions apparently.

Could you tell me why both the generator and receiver need two private interfaces? Aren't one interface which directly connects to the OVS enough to enable connection between them?

Since now you have two interfaces, how to make sure the generated packets will not be sent through the private network "gen-rcv"?

Thanks,

**Comment by mshahbaz** [comment]
The first interface is needed by vagrant for configuring and ssh'ing into the VMs. The second interface is used for sending and receiving packets. The 'gen-rcv' interface is the last interface (i.e., eth1) that you see in ifconfig. (These are vagrant related questions. Trying looking at the vagrant documentation.)

**Comment by nam1234** [comment]
I am getting this error on 'vagrant up'. 

[root@osboxes vagrant]# vagrant up
Bringing machine 'switch' up with 'libvirt' provider...
Bringing machine 'generator' up with 'libvirt' provider...
Bringing machine 'receiver' up with 'libvirt' provider...
==> receiver: Box 'pisces-ubuntu-trusty64' could not be found. Attempting to find and install...
    receiver: Box Provider: libvirt
    receiver: Box Version: >= 0
==> receiver: Box file was not detected as metadata. Adding it directly...
==> receiver: Adding box 'pisces-ubuntu-trusty64' (v0) for provider: libvirt
    receiver: Downloading: pisces-ubuntu-trusty64
==> generator: Box 'pisces-ubuntu-trusty64' could not be found. Attempting to find and install...
==> receiver: An error occurred. The error will be shown after all tasks complete.
    generator: Box Provider: libvirt
    generator: Box Version: >= 0
==> generator: Box file was not detected as metadata. Adding it directly...
==> generator: Adding box 'pisces-ubuntu-trusty64' (v0) for provider: libvirt
    generator: Downloading: pisces-ubuntu-trusty64
==> generator: An error occurred. The error will be shown after all tasks complete.
==> switch: Box 'pisces-ubuntu-trusty64' could not be found. Attempting to find and install...
    switch: Box Provider: libvirt
    switch: Box Version: >= 0
==> switch: Box file was not detected as metadata. Adding it directly...
==> switch: Adding box 'pisces-ubuntu-trusty64' (v0) for provider: libvirt
    switch: Downloading: pisces-ubuntu-trusty64
==> switch: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'switch'
machine. Please handle this error then try again:

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/osboxes/vagrant/pisces-ubuntu-trusty64

An error occurred while executing the action on the 'generator'
machine. Please handle this error then try again:

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/osboxes/vagrant/pisces-ubuntu-trusty64

An error occurred while executing the action on the 'receiver'
machine. Please handle this error then try again:

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/osboxes/vagrant/pisces-ubuntu-trusty64

The first command is working fine -
[root@osboxes osboxes]# vagrant box add pisces-ubuntu-trusty64 http://www.cs.princeton.edu/~mshahbaz/projects/pisces/vagrant/ubuntu-trusty64.box --force
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'pisces-ubuntu-trusty64' (v0) for provider: 
    box: Downloading: http://www.cs.princeton.edu/~mshahbaz/projects/pisces/vagrant/ubuntu-trusty64.box
==> box: Successfully added box 'pisces-ubuntu-trusty64' (v0) for 'virtualbox'!

How do I resolve this?
