### ISSUE TITLE
Python file instead of .sh file? 

### ISSUE THREAD

**Issue by huniyaarif1** [P4-vSwitch/vagrant#3]
While working on P4Factory, python files were used to add flows to the table. This allowed greater flexibility in testing. Can we replace l2_switch.sh in l2_switch example with something similar to routing.py in https://github.com/p4lang/p4factory/blob/master/targets/basic_routing/tests/ptf-tests/routing.py
? 
Also, can we generate and sniff packets via scapy (python) instead of using pktgen? 

I'm asking because I'm working on P4 and want to configure my code on PISCES without having to convert my python file with sh file for flow rules.
Thank you.

**Comment by mshahbaz** [comment]
Sure, can you please send me a push-request? I'd be happy to pull in your changes for the python scripts. 

You can definitely generate packets using Scapy. The transmitter and receiver are independent VMs that you can configure any way you want.
