### ISSUE TITLE
Memory requirements to run the experiment

### ISSUE THREAD

**Issue by signorello** [P4-vSwitch/vagrant#4]
I think it could be helpful to state the memory requirements to run the experiments somehow at the beginning of the main dir's README. May be, also telling that those can be easily changed by editing the VMs size in the Vagrantfile. It took me one failure before getting there since the shipped setup requires 8G (4G the switch, 2G per each generator/receiver).

Do the scripts " setup-pktgen.sh & setup-moongen.sh" serve similar purposes?

Probably, this thing was not worth opening an issue, but it was the quickest way to reach you.
Thank you for this great work

**Comment by mshahbaz** [comment]
Done. Thanks for pointing this out!

Yes, both scripts serve similar purposes. However, the MoonGen script doesn't work with the VMs for some reason (probably requires more testing/debugging). However, you can use this script to install MoonGen on a physical machine.

Btw, you can reach us using the contact info listed here, http://pisces.cs.princeton.edu/. :)
