### ISSUE TITLE
run-time rules insertion

### ISSUE THREAD

**Issue by signorello** [P4-vSwitch/vagrant#5]
Is there any automatic tool either in this repo or in same parallel project which performs translation from bmv2-like flow syntax to Flow Syntax?
Both ls_switch.sh and simple_router.sh scripts already have the canonical Flow Syntax in them.

Thank you for your time

**Comment by mshahbaz** [comment]
No, not at the moment. Sadly, you have to work this out manually. However, if you do end up writing one, we'd be happy to host your contribution on the PISCES website!
