### ISSUE TITLE
how to fill P4 tables using openflow commands

### ISSUE THREAD

**Issue by ali64Mon** [P4-vSwitch/vagrant#7]
Hi, 
Is there anyway to convert P4 flows to  OVS OpenFlow flows?
The P4 programs could contain lots of user-defined actions. Converting a P4 action to list of actions understandable by OVS OpenFlow for all P4 actions is time consuming. In other words, It would be awesome if there was  a P4 API for the OVS control plane.

Thanks for your reply in advance.

**Comment by mshahbaz** [comment]
Hi Ali,

We don't have such script, atm. There's some preliminary work done by Sean (co-author on PISCES) in the past, see here - https://github.com/P4-vSwitch/p4c-behavioral/blob/ovs/p4c_bm/flow_type_checker.py. But, I don't think it's been documented or tested. The flow_type_checker.py takes in a pickle representation of the P4 program, generated by the p4c-bm compiler; and a user can then pass rules using named actions (described in P4) with this script. I will try to ping Sean, to see, if he has some example of this, laying around.

Thanks.

**Comment by mshahbaz** [comment]
This readme file has some usage notes on the flow_type_checker.py - https://github.com/P4-vSwitch/p4c-behavioral/blob/ovs/README.md.

**Comment by ali64Mon** [comment]
Thanks for your reply @mshahbaz
